version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: store-admin-db
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: store_admin
      POSTGRES_PASSWORD: store_admin_password
      POSTGRES_DB: store_admin_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U store_admin']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
